export const PRESET_CARDS: string[] = [
    "Muy virgen por tu parte",
    "Vale, pero, ¿cuándo follamos?",
    "Si lo piensas bien, un hombre es como un dildo pero menos portátil",
    'Si digo "salud", respondes "gracias", no "qué haces dentro de mi armario"',
    "Paja espacial ✨ 🚀🚀🚀💦 ✨",
    "Me gustas",
    "¿Qué?",
    "Eso dijo ella",
    "España es el segundo país más visitado del mundo, pero tú lo superas",
    "¿ESO ES UNA REFERENCIA A MI PENE?",
    "Wow, eso ha sido más falso que su amor por mí",
    "Me dejó por alguien con mejor WiFi",
    "Te van a banear del planeta a este paso",
    "Mi abogado recomienda silencio",
    "Acabo de perder una pelea contra una puerta",
    "NOOOOOO POR EL CULO NOOOOOOO",
    "Six Seven",
    "Ostia al canto",
    "Mi planta murió decepcionada de mí",
    "Mi amigo tiene un fetiche bastante curioso",
    "Mi madre vió mi historial",
    "Lo que más me gusta de ti es tu perfil de Pornhub",
    "No era mi cuenta falsa",
    "Una secta de señoras del bingo",
    "Mi peor error a las 3 AM",
    "Guerra civil entre mis calcetines",
    "La mía venía con sorpresa y la puse en 5, tampoco pasa nada",
    "Oh, sí",
    "Ojalá tener un novio como tú. Pero guapo",
    "secso",
    "Tengo la respuesta a todas tus dudas: ¡PORNO GAY!",
    "Cariño, ¿quieres salir ya del baño, que te llevo esperando más de lo que vas a aguantar?",
    "Me gustan los micropenes",
    "so",
    "ESTRÚJAMELA",
    "uwu",
    "A mí me encantaaaa 💕💕💕",
    "Orgásmico",
    "XD",
    "Jajajaj, ¿qué coño escribe este?",
    "Wey, me mataron al aldeano de reparación",
    "Estoy en la farmacia. ¿Sigues siendo tamaño XXS en condones?",
    "¿Cuándo era el examen de lengua?",
    "Top razones por las que eres boque",
    "Si lo piensas, ¿qué nos impide follar ahora mismo en medio de la plaza?",
    "Ni te sentí dentro",
    "Mi madre me ha regañado por insultarte en sueños",
    "Cómo le gusta lo que le encanta",
    "Dedear panchitas",
    "Os envío mi pistola por correo",
    "Estará confundida, y entonces le salto del techo",
    "Agresión con manillar",
    "Muerte por banana",
    "Es importante aguantarse hasta estar dentro",
    "Ella jura",
    "Pobrecita",
    "Autistada histórica",
    'A todo esto, ¿qué es "follar"?',
    "Vale, empiezo con el tutorial. Antes de nada, debe estar erecta, así: ➀ Foto",
    "Lo haces muy bien para tener 8 años",
    "Tú sabes que este chat es el grupo, ¿verdad?",
    "Reseña honesta: tu madre está muy cara para lo que ofrece",
    ""
];

export const PRESET_STARTERS: string[] = [
    "Oye, estoy en mi casa desnudo esperándote, ¿vienes ya?",
    "Su cuarto era un museo de lubricantes",
    "¿Os parece bien que vayamos a la Warner este mes?",
    "La acabo de liar",
    "AYUDA",
    "¿Culo o tetas?",
    "¿Qué coño acaba de pasar?",
    "Necesito que alguien me explique esto.",
    "Creo que tenemos un problema.",
    "No estoy preparado para contaros lo que ha pasado.",
    "¿Quién ha sido?",
    "Tengo una pregunta bastante seria.",
    "Acabo de cometer un error.",
    "Chicos, creo que la he liado.",
    "¿Esto es normal?",
    "Necesito consejo urgentemente.",
    "¿Alguien sabe qué hacer en esta situación?",
    "Acabo de recibir el peor mensaje de mi vida.",
    "Hay algo que llevo demasiado tiempo ocultando.",
    "¿Por qué nadie me avisó de esto?",
    "Me acaba de pasar algo que no debería ser posible.",
    "No sé si reírme o preocuparme.",
    "Tengo malas noticias.",
    "Tengo buenas noticias. Creo.",
    "Esto se nos ha ido de las manos.",
    "¿Quién coño hace esto?",
    "No preguntéis cómo he llegado aquí.",
    "Necesito una excusa y la necesito ya.",
    "He tomado una decisión terrible.",
    "Creo que me he enamorado.",
    "Me acaba de escribir mi ex.",
    "¿Qué haríais vosotros?",
    "He vuelto a hablar con esa persona.",
    "No debería haberle dado mi número.",
    "Me han dejado en visto durante tres días.",
    "¿Es demasiado pronto para arrepentirme?",
    "He cometido el error de mirar su móvil.",
    "Hay una captura de pantalla que podría destruirme.",
    "Nunca debí enviar ese mensaje.",
    "Mi madre acaba de preguntarme por esto.",
    "Creo que alguien ha visto mis conversaciones.",
    "Tengo una explicación, pero no os va a gustar.",
    "¿Qué es lo más ilegal que habéis hecho?",
    "Creo que la policía sabe algo.",
    "No puedo explicar por qué hay una cabra en mi habitación.",
    "Acabo de descubrir que mi vecino tiene un secreto.",
    "Mi gato lleva horas mirando a la misma pared.",
    "Hay un señor en la calle que sabe mi nombre.",
    "¿Alguien sabe cómo deshacerse de una evidencia?",
    "No sé de quién es esta sangre.",
    "He encontrado algo debajo de mi cama.",
    "El médico me ha dicho que no vuelva a hacerlo.",
    "Creo que acabo de empezar una secta.",
    "Tengo una idea que probablemente no deberíamos hacer.",
    "¿Quién sería capaz de sobrevivir menos tiempo en una isla desierta?",
    "¿Qué haríais por un millón de euros?",
    "¿Qué sería peor encontrar en vuestro baño?",
    "¿Quién del grupo acabaría antes en prisión?",
    "Creo que alguien nos está escuchando.",
    "Acabo de recibir un mensaje de mi yo del futuro.",
    "Mi futuro yo me ha dicho que no haga esto.",
    "Hay algo debajo de la mesa.",
    "La puerta acaba de abrirse sola.",
    "Mi móvil acaba de escribir un mensaje solo.",
    "Alguien acaba de llamar a mi casa.",
    "No sé quién acaba de entrar.",
    "He encontrado una habitación que no conocía.",
    "El perro acaba de decir mi nombre.",
    "Una paloma me está siguiendo.",
    "Mi tostadora acaba de mandarme una amenaza.",
    "Creo que mi nevera está enfadada conmigo.",
    "Acabo de ser expulsado de un sitio al que nunca fui.",
    "Un desconocido acaba de darme las gracias.",
    "Me han nombrado heredero de algo.",
    "Acabo de ganar una guerra que no sabía que existía.",
    "Hay un pato sentado en mi cama.",
    "El gobierno acaba de cometer un error conmigo.",
    "Creo que he sido elegido.",
    "No sé por qué, pero el champú tiene mi contraseña."
];

for (const text of [...PRESET_CARDS, ...PRESET_STARTERS]) {
    console.log(text.length, text);
    if (text.length > 100) throw new Error(`Card ${text} exceeds character limit`);
}